version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
    image: hi2cms-ui-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - VUE_APP_API_ROOT=https://hi2cms-prod.osc-fr1.scalingo.io/
    tty: true